version: '3.7'
services:
    windows-server-core-anaconda-iis-ml:
        container_name: windows-server-core-anaconda-iis-ml
        build:
            dockerfile: docker/windows-server-core-anaconda-iis-ml.dockerfile
            context: ./
        image: sergiovallejr/windows-server-core-anaconda-iis-ml:1.4
        ports:
            - "0.0.0.0:8000:80"
        networks:
            - default
networks:
  default:
    external:
      name: nat
